"""Tests for the upgraded Lean-aware parsing pipeline."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import json
import shutil
import tempfile
import unittest

from research_orchestrator.lean_parser import (
    parse_lean_file,
    parse_lean_errors,
    parse_lean_project,
)
from research_orchestrator.aristotle_result_parser import (
    analyze_aristotle_result,
    extract_archive,
    parse_manifest,
)
from research_orchestrator.enhanced_ingestion import (
    enhanced_parse_provider_result,
    upgrade_provider_result,
)
from research_orchestrator.types import ProviderResult


# ---------------------------------------------------------------------------
# Realistic Lean file content for testing
# ---------------------------------------------------------------------------

LEAN_PARTIAL_PROOF = """\
import Mathlib

noncomputable section

namespace Erdos123

open Filter
open scoped BigOperators Pointwise

/-- The multiplicative semigroup generated by `a`, `b`, and `c`. -/
def PowTripleSet (a b c : ℕ) : Set ℕ :=
  {n | ∃ i j k : ℕ, n = a ^ i * b ^ j * c ^ k}

/-- No distinct chosen summand divides another. -/
def IsDivisionAntichain (s : Finset ℕ) : Prop :=
  ∀ ⦃x y : ℕ⦄, x ∈ s → y ∈ s → x ≠ y → ¬ x ∣ y

/-- A coverage lemma that the prover discovered as intermediate structure. -/
lemma coverage_bridge (a b c : ℕ) (h : Nat.Coprime a b) :
    ∀ᶠ n : ℕ in atTop, ∃ s : Finset ℕ,
      (↑s : Set ℕ) ⊆ PowTripleSet a b c ∧ s.sum id = n := by
  sorry

/-- The antichain extraction step was proved by the solver. -/
theorem antichain_extraction (s : Finset ℕ) (hs : s.Nonempty) :
    ∃ t : Finset ℕ, t ⊆ s ∧ IsDivisionAntichain t ∧ t.sum id = s.sum id := by
  have density_step : s.card > 0 := Finset.Nonempty.card_pos hs
  have antichain_core : True := trivial
  exact ⟨s, Finset.Subset.refl s, fun x y hx hy hne hdvd => absurd hdvd (sorry), rfl⟩

/-- Main theorem - still has sorry. -/
theorem erdos_123_main :
    ∀ a b c : ℕ, 1 < a → 1 < b → 1 < c →
      True := by
  intro a b c ha hb hc
  have bridge := coverage_bridge a b c
  sorry

end Erdos123
"""

LEAN_COMPLETE_PROOF = """\
import Mathlib

theorem simple_demo : True := by
  trivial

lemma helper_lemma (n : ℕ) : n = n := by
  rfl
"""

LEAN_ERROR_OUTPUT = """\
/workspace/Main.lean:15:2: error: unsolved goals
case h
a b c : ℕ
ha : 1 < a
hb : 1 < b
hc : 1 < c
⊢ IsDComplete (PowTripleSet a b c)

/workspace/Main.lean:28:4: warning: declaration uses 'sorry'

/workspace/Main.lean:42:0: error: deterministic timeout [300000]
"""


class LeanParserTest(unittest.TestCase):
    def setUp(self):
        self.tempdir = Path(tempfile.mkdtemp(prefix="lean_parser_test_"))

    def tearDown(self):
        shutil.rmtree(self.tempdir, ignore_errors=True)

    def test_parse_partial_proof_extracts_declarations_and_sorries(self):
        lean_file = self.tempdir / "Main.lean"
        lean_file.write_text(LEAN_PARTIAL_PROOF, encoding="utf-8")

        analysis = parse_lean_file(str(lean_file))

        self.assertEqual(analysis.imports, ["Mathlib"])
        self.assertIn("Erdos123", analysis.namespaces)
        self.assertGreaterEqual(len(analysis.declarations), 4)

        # Should find sorry locations
        self.assertGreater(analysis.sorry_count, 0)
        sorry_decls = {s.enclosing_declaration for s in analysis.sorry_locations}
        self.assertIn("coverage_bridge", sorry_decls)
        self.assertIn("erdos_123_main", sorry_decls)

        # Should find intermediate results
        intermediate_names = [d.name for d in analysis.intermediate_results]
        self.assertTrue(
            any("density_step" in name or "antichain_core" in name for name in intermediate_names),
            f"Expected intermediate results, got: {intermediate_names}",
        )

    def test_parse_complete_proof_has_no_sorries(self):
        lean_file = self.tempdir / "Complete.lean"
        lean_file.write_text(LEAN_COMPLETE_PROOF, encoding="utf-8")

        analysis = parse_lean_file(str(lean_file))

        self.assertEqual(analysis.sorry_count, 0)
        self.assertGreater(analysis.completed_count, 0)
        completed_names = [d.name for d in analysis.completed_proofs]
        self.assertIn("simple_demo", completed_names)
        self.assertIn("helper_lemma", completed_names)

    def test_parse_error_output_extracts_goals_and_errors(self):
        errors, tactic_states = parse_lean_errors(LEAN_ERROR_OUTPUT)

        # Should find structured errors
        self.assertGreaterEqual(len(errors), 2)
        error_categories = {e.category for e in errors}
        self.assertIn("timeout", error_categories)
        self.assertIn("sorry", error_categories)

        # Should find tactic state with goal
        self.assertGreaterEqual(len(tactic_states), 1)
        all_goals = [g for ts in tactic_states for g in ts.goals]
        self.assertTrue(
            any("IsDComplete" in g for g in all_goals),
            f"Expected IsDComplete goal, got: {all_goals}",
        )

    def test_parse_project_aggregates_across_files(self):
        (self.tempdir / "Main.lean").write_text(LEAN_PARTIAL_PROOF, encoding="utf-8")
        (self.tempdir / "Helper.lean").write_text(LEAN_COMPLETE_PROOF, encoding="utf-8")

        project = parse_lean_project(str(self.tempdir))

        self.assertEqual(len(project.files), 2)
        self.assertGreater(project.total_sorry_count, 0)
        self.assertGreater(project.total_completed_count, 0)

    def test_dependency_extraction(self):
        lean_file = self.tempdir / "Deps.lean"
        lean_file.write_text(
            "theorem uses_helpers : True := by\n"
            "  apply And.intro\n"
            "  exact trivial\n"
            "  rw [Nat.add_comm]\n"
            "  simp [List.map]\n",
            encoding="utf-8",
        )
        analysis = parse_lean_file(str(lean_file))
        all_deps = []
        for d in analysis.declarations:
            all_deps.extend(d.dependencies)
        self.assertTrue(
            any("And.intro" in dep or "Nat.add_comm" in dep for dep in all_deps),
            f"Expected dependency extraction, got: {all_deps}",
        )


class AristotleResultParserTest(unittest.TestCase):
    def setUp(self):
        self.tempdir = Path(tempfile.mkdtemp(prefix="aristotle_result_parser_test_"))

    def tearDown(self):
        shutil.rmtree(self.tempdir, ignore_errors=True)

    def test_analyze_lean_artifacts_produces_structured_observations(self):
        lean_file = self.tempdir / "Main.lean"
        lean_file.write_text(LEAN_PARTIAL_PROOF, encoding="utf-8")

        result = analyze_aristotle_result(
            artifact_paths=[str(lean_file)],
            stderr=LEAN_ERROR_OUTPUT,
        )

        self.assertTrue(result.has_meaningful_content())
        self.assertGreater(len(result.unsolved_goals), 0)
        self.assertGreater(result.sorry_count, 0)

    def test_analyze_complete_proof_classifies_as_proved(self):
        lean_file = self.tempdir / "Complete.lean"
        lean_file.write_text(LEAN_COMPLETE_PROOF, encoding="utf-8")

        result = analyze_aristotle_result(
            artifact_paths=[str(lean_file)],
            stdout="Proof complete. All goals solved.",
        )

        self.assertEqual(result.verification_status, "proved")
        self.assertGreater(len(result.proved_lemmas), 0)

    def test_manifest_parsing(self):
        manifest_path = self.tempdir / "manifest.json"
        manifest_path.write_text(
            json.dumps({
                "project_id": "abc-123",
                "status": "COMPLETE",
                "sorries_filled": 3,
                "sorries_remaining": 1,
                "theorems_proved": ["antichain_extraction"],
            }),
            encoding="utf-8",
        )

        manifest = parse_manifest(str(manifest_path))

        self.assertEqual(manifest.project_id, "abc-123")
        self.assertEqual(manifest.status, "COMPLETE")
        self.assertEqual(manifest.sorries_filled, 3)
        self.assertIn("antichain_extraction", manifest.theorems_proved)

    def test_workspace_analysis_finds_lean_files(self):
        workspace = self.tempdir / "project"
        workspace.mkdir()
        (workspace / "Main.lean").write_text(LEAN_PARTIAL_PROOF, encoding="utf-8")
        (workspace / "Helper.lean").write_text(LEAN_COMPLETE_PROOF, encoding="utf-8")

        result = analyze_aristotle_result(
            artifact_paths=[],
            workspace_dir=str(workspace),
        )

        self.assertTrue(result.has_meaningful_content())
        self.assertGreater(result.completed_count, 0)


class EnhancedIngestionTest(unittest.TestCase):
    def setUp(self):
        self.tempdir = Path(tempfile.mkdtemp(prefix="enhanced_ingestion_test_"))

    def tearDown(self):
        shutil.rmtree(self.tempdir, ignore_errors=True)

    def test_enhanced_parser_extracts_more_signal_than_regex(self):
        lean_file = self.tempdir / "Main.lean"
        lean_file.write_text(LEAN_PARTIAL_PROOF, encoding="utf-8")

        result = ProviderResult(
            status="succeeded",
            blocker_type="unknown",
            raw_stdout="",
            raw_stderr=LEAN_ERROR_OUTPUT,
            artifacts=[str(lean_file)],
            metadata={"provider_name": "aristotle-cli"},
        )

        # Regex-only (existing)
        from research_orchestrator.result_ingestion import parse_provider_result
        regex_record = parse_provider_result(result)

        # Lean-aware (upgraded)
        enhanced_record = enhanced_parse_provider_result(result)

        # Enhanced should find more content
        self.assertGreaterEqual(
            len(enhanced_record.proved_lemmas) + len(enhanced_record.generated_lemmas),
            len(regex_record.proved_lemmas) + len(regex_record.generated_lemmas),
        )
        self.assertGreaterEqual(
            len(enhanced_record.unsolved_goals),
            len(regex_record.unsolved_goals),
        )
        self.assertGreaterEqual(
            len(enhanced_record.proof_traces),
            len(regex_record.proof_traces),
        )
        # Enhanced should have lean-aware provenance
        self.assertEqual(enhanced_record.provider.adapter_name, "lean-aware-verification-adapter")

    def test_upgrade_provider_result_enriches_without_breaking(self):
        lean_file = self.tempdir / "Main.lean"
        lean_file.write_text(LEAN_COMPLETE_PROOF, encoding="utf-8")

        result = ProviderResult(
            status="succeeded",
            blocker_type="unknown",
            proved_lemmas=["original_lemma : True"],
            artifacts=[str(lean_file)],
            metadata={"provider_name": "mock"},
        )

        upgraded = upgrade_provider_result(result)

        # Should keep original content
        self.assertIn("original_lemma : True", upgraded.proved_lemmas)
        # Should add Lean-extracted content
        self.assertGreater(len(upgraded.proved_lemmas), 1)
        # Should add metadata
        self.assertIn("lean_completed_count", upgraded.metadata)

    def test_fallback_when_no_lean_artifacts(self):
        result = ProviderResult(
            status="failed",
            blocker_type="dns_failure",
            raw_stderr="Could not resolve host",
            metadata={"provider_name": "aristotle-cli"},
        )

        record = enhanced_parse_provider_result(result)

        # Should fall back to regex-based parsing gracefully
        self.assertIn(record.verification_status, {"infra_failure", "unknown"})
        self.assertEqual(record.provider.adapter_name, "structured-verification-adapter")

    def test_mixed_sorry_and_complete_classified_as_partial(self):
        lean_file = self.tempdir / "Mixed.lean"
        lean_file.write_text(LEAN_PARTIAL_PROOF, encoding="utf-8")

        result = ProviderResult(
            status="succeeded",
            blocker_type="unknown",
            artifacts=[str(lean_file)],
            metadata={"provider_name": "aristotle-cli"},
        )

        record = enhanced_parse_provider_result(result)

        self.assertEqual(record.verification_status, "partial")
        self.assertTrue(record.proved_lemmas or record.generated_lemmas)
        self.assertTrue(record.unsolved_goals or record.proof_traces)


if __name__ == "__main__":
    unittest.main()
