/-
Experiment ID: e50d69d6-a424-48bc-a4c3-ec2e3e46c62e
Move: underspecify
Phase: mapping
Modification: {"mode": "minimal_context"}
-/

noncomputable section

namespace Erdos123

open Filter
open scoped BigOperators Pointwise

/-- The multiplicative semigroup generated by `a`, `b`, and `c`. -/
def PowTripleSet (a b c : ℕ) : Set ℕ :=
  {n | ∃ i j k : ℕ, n = a ^ i * b ^ j * c ^ k}

/-- Pairwise coprimality for a triple of natural numbers. -/
def PairwiseCoprime3 (a b c : ℕ) : Prop :=
  Nat.Coprime a b ∧ Nat.Coprime a c ∧ Nat.Coprime b c

/-- No distinct chosen summand divides another. -/
def IsDivisionAntichain (s : Finset ℕ) : Prop :=
  ∀ ⦃x y : ℕ⦄, x ∈ s → y ∈ s → x ≠ y → ¬ x ∣ y

/-- A set is `d`-complete if all sufficiently large integers admit such an
antichain sum representation. -/
def IsDComplete (A : Set ℕ) : Prop :=
  ∀ᶠ n : ℕ in atTop, ∃ s : Finset ℕ,
    (↑s : Set ℕ) ⊆ A ∧ IsDivisionAntichain s ∧ s.sum id = n

/-- A workspace-local Lean 4 stub for Erdos Problem 123. The formal-conjectures repo
contains a current statement very close to this one together with solved variants. -/
theorem erdos_123_d_complete_sequences :
    ∀ a b c : ℕ, 1 < a → 1 < b → 1 < c →
      PairwiseCoprime3 a b c →
      IsDComplete (PowTripleSet a b c) := by
  sorry

end Erdos123
