/-
Experiment ID: d2ade9ef-785c-4c1a-80c9-e3396c7e3ecd
Move: reformulate
Move family: extremal_case
Theorem family: erdos_problem
Phase: consolidation
Modification: {"extremal_target": "smooth_subset_sum_complete:     \u2200\u1da0 n : \u2115 in atTop, \u2203 s : Finset \u2115,\n      (\u2191s : Set \u2115) \u2286 PowTripleSet a b c \u2227 s.sum id = n := by"}
-/

-- erdos family workspace
-- focus: extremal constructions, additive structure, and parameter boundary behavior
-- erdos-123 focus: d-completeness, divisibility antichains, and reusable covering lemmas
-- extremal sweep: smooth_subset_sum_complete:     ∀ᶠ n : ℕ in atTop, ∃ s : Finset ℕ,
      (↑s : Set ℕ) ⊆ PowTripleSet a b c ∧ s.sum id = n := by
import Mathlib

noncomputable section

namespace Erdos123

open Filter
open scoped BigOperators Pointwise

/-- The multiplicative semigroup generated by `a`, `b`, and `c`. -/
def PowTripleSet (a b c : ℕ) : Set ℕ :=
  {n | ∃ i j k : ℕ, n = a ^ i * b ^ j * c ^ k}

/-- Pairwise coprimality for a triple of natural numbers. -/
def PairwiseCoprime3 (a b c : ℕ) : Prop :=
  Nat.Coprime a b ∧ Nat.Coprime a c ∧ Nat.Coprime b c

/-- No distinct chosen summand divides another. -/
def IsDivisionAntichain (s : Finset ℕ) : Prop :=
  ∀ ⦃x y : ℕ⦄, x ∈ s → y ∈ s → x ≠ y → ¬ x ∣ y

/-- A set is `d`-complete if all sufficiently large integers admit such an
antichain sum representation. -/
def IsDComplete (A : Set ℕ) : Prop :=
  ∀ᶠ n : ℕ in atTop, ∃ s : Finset ℕ,
    (↑s : Set ℕ) ⊆ A ∧ IsDivisionAntichain s ∧ s.sum id = n

/-- A workspace-local Lean 4 stub for Erdos Problem 123. The formal-conjectures repo
contains a current statement very close to this one together with solved variants. -/
theorem erdos_123_d_complete_sequences :
    ∀ a b c : ℕ, 1 < a → 1 < b → 1 < c →
      PairwiseCoprime3 a b c →
      IsDComplete (PowTripleSet a b c) := by
  sorry

end Erdos123
