/-
Experiment ID: 423988c8-0bd7-439f-a321-007b0d68953b
Move: reformulate
Move family: extremal_case
Theorem family: erdos_problem
Phase: consolidation
Modification: {"extremal_target": "both inclusions. For \u2286: if n = 2^i * 4^j * 8^k = 2^i * 2^(2j) * 2^(3k) = 2^(i+2j+3k), take m = i+2j+3k. For \u2287: if n = 2^m, take i=m, j=0, k=0, then n = 2^m * 4^0 * 8^0 = 2^m * 1 * 1 = 2^m."}
-/

-- erdos family workspace
-- focus: extremal constructions, additive structure, and parameter boundary behavior
-- erdos-123 focus: d-completeness, divisibility antichains, and reusable covering lemmas
-- extremal sweep: both inclusions. For ⊆: if n = 2^i * 4^j * 8^k = 2^i * 2^(2j) * 2^(3k) = 2^(i+2j+3k), take m = i+2j+3k. For ⊇: if n = 2^m, take i=m, j=0, k=0, then n = 2^m * 4^0 * 8^0 = 2^m * 1 * 1 = 2^m.
import Mathlib

noncomputable section

namespace Erdos123

open Filter
open scoped BigOperators Pointwise

/-- The multiplicative semigroup generated by `a`, `b`, and `c`. -/
def PowTripleSet (a b c : ℕ) : Set ℕ :=
  {n | ∃ i j k : ℕ, n = a ^ i * b ^ j * c ^ k}

/-- Pairwise coprimality for a triple of natural numbers. -/
def PairwiseCoprime3 (a b c : ℕ) : Prop :=
  Nat.Coprime a b ∧ Nat.Coprime a c ∧ Nat.Coprime b c

/-- No distinct chosen summand divides another. -/
def IsDivisionAntichain (s : Finset ℕ) : Prop :=
  ∀ ⦃x y : ℕ⦄, x ∈ s → y ∈ s → x ≠ y → ¬ x ∣ y

/-- A set is `d`-complete if all sufficiently large integers admit such an
antichain sum representation. -/
def IsDComplete (A : Set ℕ) : Prop :=
  ∀ᶠ n : ℕ in atTop, ∃ s : Finset ℕ,
    (↑s : Set ℕ) ⊆ A ∧ IsDivisionAntichain s ∧ s.sum id = n

/-- A workspace-local Lean 4 stub for Erdos Problem 123. The formal-conjectures repo
contains a current statement very close to this one together with solved variants. -/
theorem erdos_123_d_complete_sequences :
    ∀ a b c : ℕ, 1 < a → 1 < b → 1 < c →
      PairwiseCoprime3 a b c →
      IsDComplete (PowTripleSet a b c) := by
  sorry

end Erdos123
